name: Build

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '20'
    outputs:
      version: 
        description: 'The extracted project version'
        value: string

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: Extract project version
        id: extract-version
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
              if [[ "${{ github.event.release.tag_name }}" == v* ]]; then
                  version=${{ github.event.release.tag_name }}
                  echo "release_version=${version:1}" >> $GITHUB_ENV
                  echo "::set-output name=release_version::${version:1}"
              else
                  echo "release_version=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
                  echo "::set-output name=release_version::${{ github.event.release.tag_name }}"
              fi
          else
             version=$(node -p "require('./package.json').version")
             echo "release_version=${version}" >> $GITHUB_ENV
             echo "::set-output name=release_version::${version}" 
          fi
